### ZIP：

假设你有以下两个列表：

```python
names = ["Alice", "Bob", "Charlie", "Diana"]
scores = [85, 90, 78, 92]
```

1. 使用 `zip` 函数将 `names` 和 `scores` 结合，生成一个表示学生姓名和分数的列表，其中每个元素都是一个元组 `(name, score)`。
2. 使用列表解析，将分数大于等于 80 的学生名字提取出来，存储到一个新的列表中。

### 输出示例：

根据上述输入，程序的输出应该是：

```python
[('Alice', 85), ('Bob', 90), ('Charlie', 78), ('Diana', 92)]
['Alice', 'Bob', 'Diana']
```

### 代码框架：

请在下方的代码框架中完成代码：

```python
names = ["Alice", "Bob", "Charlie", "Diana"]
scores = [85, 90, 78, 92]

# 第一步：使用 zip 函数
combined = ...

# 打印组合后的列表
print(combined)

# 第二步：筛选分数大于等于 80 的学生名字
filtered_names = ...

# 打印筛选结果
print(filtered_names)
```

### 使用 `enumerate`

假设你有一个列表，存储了班级学生的姓名：

```python
students = ["Alice", "Bob", "Charlie", "Diana"]
```

1. 使用 `enumerate` 为每个学生分配一个学号（从 1 开始）。
2. 将分配的学号和姓名存储为一个元组，最终生成一个包含所有学生信息的列表。
3. 使用列表解析完成以上任务，并打印最终的结果。

### 输出示例：
运行代码后，结果应为：

```python
[(1, 'Alice'), (2, 'Bob'), (3, 'Charlie'), (4, 'Diana')]
```

### 提示：
- `enumerate(iterable, start)` 可以接收 `start` 参数，用于指定枚举的起始值。

### 代码框架：
请在以下代码框架中完成任务：

```python
students = ["Alice", "Bob", "Charlie", "Diana"]

# 使用 enumerate 完成学号分配
student_info = ...

# 打印结果
print(student_info)
```

### 使用 `lambda` 表达式

假设你有一个整数列表：

```python
numbers = [12, 5, 8, 15, 24, 7, 30, 19]
```

1. 使用 `lambda` 表达式和 `filter` 函数，筛选出列表中所有能被 5 整除的数字。
2. 使用 `lambda` 表达式和 `map` 函数，将列表中的每个数字平方后生成一个新的列表。
3. 分别打印出筛选后的结果和平方后的列表。

---

### 输出示例：
对于上述 `numbers`，代码的输出应该是：

筛选出能被 5 整除的数字：
```python
[5, 15, 30]
```

将每个数字平方后的新列表：
```python
[144, 25, 64, 225, 576, 49, 900, 361]
```

---

### 提示：
- `filter(function, iterable)` 用于过滤列表，`function` 返回值为 `True` 的元素会被保留。
- `map(function, iterable)` 用于将 `function` 应用到列表的每个元素上，返回一个新的迭代器。

---

### 代码框架：
请在以下代码框架中完成任务：

```python
numbers = [12, 5, 8, 15, 24, 7, 30, 19]

# 使用 lambda 和 filter 筛选能被 5 整除的数字
divisible_by_5 = ...

# 使用 lambda 和 map 将每个数字平方
squared_numbers = ...

# 打印结果
print(list(divisible_by_5))
print(list(squared_numbers))
```

In [80]:
d1 = {v:k for k, v in d.items()}
d2= {k for k in d}
d3 = [v for _,v in d.items()]
d4 = [k for k, v in d.items() if v%2==1]

print(d1,d2,d3,d4)

{17: 'a', 20: 'b', 25: 'c'} {'b', 'a', 'c'} [17, 20, 25] ['a', 'c']


### 简单解释

1. **`*` 解包**：将序列（如列表、元组）解开成位置参数传递给函数。  
2. **`**` 解包**：将字典的键值对解开成关键字参数传递给函数。

---

### 练习题

假设你有以下函数和变量：

```python
def display_info(name, age, city, country):
    print(f"{name}, {age}, lives in {city}, {country}.")
    
args = ["Alice", 30]
kwargs = {"city": "Galway", "country": "Ireland"}
```

**任务**：
1. 使用 `*` 和 `**` 同时传递 `args` 和 `kwargs` 给函数 `display_info`，让它正确输出信息。  
2. 扩展 `args` 或 `kwargs` 来输出 `Bob, 25, lives in Dublin, Ireland.`

### 使用 `yield` 生成器

编写一个生成器函数 `countdown(n)`，它接受一个整数 `n`，并从 `n` 倒数到 `0`，每次返回一个值。同时在每次生成值时打印 `Counting down: x`，其中 `x` 是当前的倒数值。

**任务要求**：
1. 实现生成器函数 `countdown(n)`。
2. 使用 `for` 循环调用该生成器函数并打印每次返回的值。
3. 在倒数结束后，打印 `"Countdown finished!"`。

---

### 输出示例：
当调用 `countdown(5)` 时，程序输出应该是：

```plaintext
Counting down: 5
5
Counting down: 4
4
Counting down: 3
3
Counting down: 2
2
Counting down: 1
1
Counting down: 0
0
Countdown finished!
``` 

---

### 提示：
- 使用 `yield` 关键字可以暂停生成器的执行并返回一个值。
- 每次迭代会从上次暂停的地方继续。

### 题目：使用 `range` 实现倒序和步长控制

编写一个函数 `reverse_print(start, stop, step)`，该函数实现以下功能：

1. 使用 `range` 倒序打印从 `start` 到 `stop`（不包括 `stop`）的数字，步长为 `step`。
2. 确保当 `start` 小于 `stop` 时，不打印任何数字，并提示 `"Invalid range for reverse counting"`。

---

### 输出示例：

#### 示例 1：
调用：
```python
reverse_print(10, 0, 2)
```

输出：
```plaintext
10
8
6
4
2
```

#### 示例 2：
调用：
```python
reverse_print(5, 10, 2)
```

输出：
```plaintext
Invalid range for reverse counting
```

#### 示例 3：
调用：
```python
reverse_print(15, 5, 3)
```

输出：
```plaintext
15
12
9
6
```

---

### 提示：
- 使用 `range(start, stop, step)` 生成倒序数字。
- `step` 必须是负数，否则倒序无效。
- 检查 `start > stop` 确保倒序合法。

In [ ]:
def reverse_print(start,stop, step):
    if start<stop:
        print("Invalid range for reverse counting")
        return 
    for i in range(start, stop, step):
        print(i)

### 使用 `yield` 实现斐波那契数列生成器

编写一个生成器函数 `fibonacci(n)`，它生成前 `n` 个斐波那契数。斐波那契数列的定义如下：

- 第一个数为 `0`，第二个数为 `1`。
- 从第三个数开始，每个数是前两个数的和。

**任务要求**：

1. 实现生成器函数 `fibonacci(n)`，每次调用生成下一个斐波那契数。
2. 使用 `for` 循环调用生成器函数，打印出前 `n` 个斐波那契数。

---

### 输出示例：

#### 示例 1：
调用：
```python
for num in fibonacci(7):
    print(num)
```

输出：
```plaintext
0
1
1
2
3
5
8
```

#### 示例 2：
调用：
```python
for num in fibonacci(10):
    print(num)
```

输出：
```plaintext
0
1
1
2
3
5
8
13
21
34
```

---

### 提示：

- 使用两个变量 `a` 和 `b` 表示前两个斐波那契数，初始化为 `0` 和 `1`。
- 每次生成一个斐波那契数后，更新 `a` 和 `b` 的值：`a, b = b, a + b`。

In [66]:
def fibonacci(n):
    list = []
    for i in range(n):
        if i <= 1: 
            list.append(i)
            yield i
        
        else:
            s = list[i-1]+list[i-2]
            list.append(s)
            yield s




In [67]:
for i in fibonacci(10):
    print(i)

0
1
1
2
3
5
8
13
21
34


### 使用 `yield from` 合并多个生成器

编写一个生成器函数 `chain_generators(gen1, gen2)`，它将两个生成器 `gen1` 和 `gen2` 的输出合并到一起，使用 `yield from` 来实现合并。

**要求**：
1. 实现生成器函数 `chain_generators(gen1, gen2)`。
2. 创建两个生成器：
   - `gen1`：生成 1 到 3 的数字。
   - `gen2`：生成 'a' 到 'c' 的字符。
3. 调用 `chain_generators(gen1, gen2)`，依次输出两个生成器的内容。

---

### 输出示例：
调用以下代码：
```python
def gen1():
    for i in range(1, 4):
        yield i

def gen2():
    for char in 'abc':
        yield char

for item in chain_generators(gen1(), gen2()):
    print(item)
```

**输出**：
```plaintext
1
2
3
a
b
c
```

---

### 提示：
- `yield from` 可以直接委托生成器的生成任务，而无需手动迭代。
- 可以将 `yield from` 分别用在 `gen1` 和 `gen2` 的生成逻辑中。

In [68]:
def chain_generators(gen1,gen2):
    yield from gen1()
    yield from gen2()

def gen1():
    for i in range(3):
        yield i+1

def gen2():
    for char in 'abc':
        yield char

        
for item in chain_generators(gen1, gen2):
    print(item)


### 练习题：使用 `itertools` 生成笛卡尔积和排列

假设你有两个列表：

```python
colors = ["red", "green", "blue"]
shapes = ["circle", "square"]
```

**任务**：

1. 使用 `itertools.product` 生成所有可能的颜色和形状的组合。
2. 使用 `itertools.permutations` 生成所有颜色的排列组合，长度为 2。
3. 打印生成的笛卡尔积和排列组合。

---

### 输出示例

#### 笛卡尔积：
```plaintext
('red', 'circle')
('red', 'square')
('green', 'circle')
('green', 'square')
('blue', 'circle')
('blue', 'square')
```

#### 排列组合：
```plaintext
('red', 'green')
('red', 'blue')
('green', 'red')
('green', 'blue')
('blue', 'red')
('blue', 'green')
```

---

### 提示

- `itertools.product(*iterables)`：生成输入可迭代对象的笛卡尔积。
- `itertools.permutations(iterable, r)`：生成给定长度 `r` 的排列。

---

### 代码框架

请完成以下代码框架：

```python
from itertools import product, permutations

colors = ["red", "green", "blue"]
shapes = ["circle", "square"]

# 生成笛卡尔积
cartesian_product = ...

# 生成排列组合
color_permutations = ...

# 打印结果
print("笛卡尔积:")
for item in cartesian_product:
    print(item)

print("\n排列组合:")
for item in color_permutations:
    print(item)
```

In [71]:
colors = ["red", "green", "blue"]
shapes = ["circle", "square"]

In [72]:
import itertools

for i in itertools.product(colors,shapes):
    print(i)

for i in itertools.permutations(colors,r=2):
    print(i)

('red', 'circle')
('red', 'square')
('green', 'circle')
('green', 'square')
('blue', 'circle')
('blue', 'square')


### 使用 Python 的 `doctest`

编写一个函数 `is_palindrome(s)`，用于判断一个字符串是否是回文（正读和反读相同）。为该函数添加 `doctest` 测试，确保函数能够正确处理以下情况：

1. 空字符串是回文。
2. 单个字符的字符串是回文。
3. 能够正确判断普通的回文和非回文字符串。

---

### 要求

1. 实现函数 `is_palindrome(s)`。
2. 为函数添加 `doctest`，包含至少 3 个测试用例。
3. 使用 `doctest` 运行测试。

---

### 示例代码框架

```python
def is_palindrome(s):
    """
    判断字符串是否是回文。

    >>> is_palindrome("")
    True
    >>> is_palindrome("a")
    True
    >>> is_palindrome("radar")
    True
    >>> is_palindrome("hello")
    False
    >>> is_palindrome("level")
    True
    """
    # 实现逻辑
    pass

if __name__ == "__main__":
    import doctest
    doctest.testmod()
```

---

### 示例运行结果

使用 `python script_name.py` 运行脚本时：

如果代码正确，无输出；否则输出失败的测试用例。

**正确运行示例：**
无任何输出，表示所有测试通过。

**错误运行示例：**
```plaintext
**********************************************************************
File "script_name.py", line 6, in __main__.is_palindrome
Failed example:
    is_palindrome("hello")
Expected:
    False
Got:
    True
**********************************************************************
1 items had failures:
   1 of   5 in __main__.is_palindrome
***Test Failed*** 1 failures.
```

In [85]:
def is_palindrome(s):
    """
    >>> is_palindrome('a')
    True
    >>> is_palindrome('aba')
    True
    >>> is_palindrome('ddafad')
    False
    """
    if len(s) <= 1:return True
    elif s[0] != s[-1]: return False
    else: return is_palindrome(s[1:-1])

if __name__ == "__main__":
    import doctest
    doctest.testmod()

### 使用 NumPy 进行数组操作

编写一个函数 `array_operations`，完成以下任务：

1. 创建一个 3x3 的 NumPy 数组，元素为从 1 到 9 的整数。
2. 计算数组中所有元素的总和。
3. 计算每一列的平均值。
4. 将数组的每个元素乘以 2，生成一个新的数组。
5. 将新的数组展平为一维数组。

---

### 示例

调用以下代码：

```python
array_operations()
```

**输出**：
```plaintext
原始数组：
[[1 2 3]
 [4 5 6]
 [7 8 9]]

数组元素总和：
45

每列的平均值：
[4. 5. 6.]

每个元素乘以 2 的新数组：
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

展平的新数组：
[ 2  4  6  8 10 12 14 16 18]
```

---

### 提示

1. 使用 `numpy.arange` 和 `numpy.reshape` 创建 3x3 数组。
2. 使用 `.sum()` 方法计算总和。
3. 使用 `.mean(axis=0)` 计算列平均值。
4. 直接对数组执行乘法操作（如 `array * 2`）。
5. 使用 `.flatten()` 将数组展平为一维。

---

### 代码框架

```python
import numpy as np

def array_operations():
    # 创建一个 3x3 的数组
    array = ...

    # 计算数组的总和
    total_sum = ...

    # 计算每列的平均值
    column_mean = ...

    # 将每个元素乘以 2，生成新数组
    new_array = ...

    # 展平为一维数组
    flattened_array = ...

    # 打印结果
    print("原始数组：")
    print(array)

    print("\n数组元素总和：")
    print(total_sum)

    print("\n每列的平均值：")
    print(column_mean)

    print("\n每个元素乘以 2 的新数组：")
    print(new_array)

    print("\n展平的新数组：")
    print(flattened_array)
```

In [96]:
import numpy as np

def array_operations():
    # 创建一个 3x3 的数组
    array = np.arange(1,10,1).reshape((3,3))

    # 计算数组的总和
    total_sum = np.sum(array)

    # 计算每列的平均值
    column_mean = np.mean(array,axis=0)

    # 将每个元素乘以 2，生成新数组
    new_array = array * 2

    # 展平为一维数组
    flattened_array = array.flatten()

    # 打印结果
    print("原始数组：")
    print(array)

    print("\n数组元素总和：")
    print(total_sum)

    print("\n每列的平均值：")
    print(column_mean)

    print("\n每个元素乘以 2 的新数组：")
    print(new_array)

    print("\n展平的新数组：")
    print(flattened_array)

In [97]:
array_operations()

原始数组：
[[1 2 3]
 [4 5 6]
 [7 8 9]]

数组元素总和：
45

每列的平均值：
[4. 5. 6.]

每个元素乘以 2 的新数组：
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

展平的新数组：
[1 2 3 4 5 6 7 8 9]


### 练习题：使用 NumPy 的广播机制进行数组操作

#### 题目描述

1. 创建一个形状为 `(3, 1)` 的二维数组 `A`，内容为 `[[1], [2], [3]]`。
2. 创建一个形状为 `(1, 4)` 的二维数组 `B`，内容为 `[[10, 20, 30, 40]]`。
3. 使用广播机制计算数组 `C = A + B`，并打印结果。
4. 解释广播机制是如何工作的。

---

#### 示例代码框架

```python
import numpy as np

# 创建数组 A 和 B
A = ...
B = ...

# 使用广播机制进行加法
C = ...

# 打印结果
print("Array A:")
print(A)

print("\nArray B:")
print(B)

print("\nArray C (A + B):")
print(C)
```

---

#### 预期输出

```
Array A:
[[1]
 [2]
 [3]]

Array B:
[[10 20 30 40]]

Array C (A + B):
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]
```

---

#### 提示

1. **广播机制**：
   - NumPy 会在两个数组的形状不同但兼容时，自动扩展较小的数组。
   - 规则：
     - 如果数组维度不同，NumPy 会将较低维的数组在前面补充 1。
     - 如果两个数组的某一维长度不一致，但其中一个为 1，NumPy 会将其扩展为较大的长度。

2. **数组的形状**：
   - `A` 的形状为 `(3, 1)`，可以在第二维扩展为 `(3, 4)`。
   - `B` 的形状为 `(1, 4)`，可以在第一维扩展为 `(3, 4)`。

---

完成代码后，请尝试运行并观察结果，同时解释广播机制的工作原理。

In [101]:
# 创建数组 A 和 B
A = np.linspace(1,3,3).reshape(3,1)
B = np.arange(10,50,10).reshape(1,4)

# 使用广播机制进行加法
C = A + B

# 打印结果
print("Array A:")
print(A)

print("\nArray B:")
print(B)

print("\nArray C (A + B):")
print(C)

Array A:
[[1.]
 [2.]
 [3.]]

Array B:
[[10 20 30 40]]

Array C (A + B):
[[11. 21. 31. 41.]
 [12. 22. 32. 42.]
 [13. 23. 33. 43.]]


### 练习题：调整两个不能广播的数组，使其可以广播

#### 题目描述

1. 创建两个数组：
   - 数组 `A`：形状为 `(3, 2)`，值为：
     ```plaintext
     [[1, 2],
      [3, 4],
      [5, 6]]
     ```
   - 数组 `B`：形状为 `(2, 3)`，值为：
     ```plaintext
     [[10, 20, 30],
      [40, 50, 60]]
     ```
2. `A` 和 `B` 的形状不兼容，无法直接进行广播。调整它们的形状，使其可以进行加法广播操作。
3. 打印调整后的数组形状和加法结果。

---

### 示例代码框架

```python
import numpy as np

# 定义数组 A 和 B
A = np.array([[1, 2], [3, 4], [5, 6]])  # 形状 (3, 2)
B = np.array([[10, 20, 30], [40, 50, 60]])  # 形状 (2, 3)

# 调整 A 和 B 的形状，使其可以广播
A_adjusted = ...
B_adjusted = ...

# 进行加法运算
result = ...

# 打印结果
print("调整后的 A 的形状：", A_adjusted.shape)
print("调整后的 B 的形状：", B_adjusted.shape)
print("\n加法结果：")
print(result)
```

---

### 提示

1. 使用 `np.reshape` 或 `np.newaxis` 手动调整数组的维度：
   - 添加新轴以扩展数组的维度。
   - 使两个数组的形状最终兼容。

2. 最终调整后的形状：
   - `A_adjusted` 的形状应该是 `(3, 2, 1)`。
   - `B_adjusted` 的形状应该是 `(1, 2, 3)`。

3. 广播后，两个数组的形状将变为 `(3, 2, 3)`。

---

完成后，观察结果并尝试总结广播调整的过程。

In [103]:
# 定义数组 A 和 B
A = np.array([[1, 2], [3, 4], [5, 6]])  # 形状 (3, 2)
B = np.array([[10, 20, 30], [40, 50, 60]])  # 形状 (2, 3)

# 调整 A 和 B 的形状，使其可以广播
A_adjusted = A.reshape(3,2,1)
B_adjusted = B.reshape(1,2,3)

# 进行加法运算
result = A_adjusted+B_adjusted

# 打印结果
print("调整后的 A 的形状：", A_adjusted.shape)
print("调整后的 B 的形状：", B_adjusted.shape)
print("\n加法结果：")
print(result)

调整后的 A 的形状： (3, 2, 1)
调整后的 B 的形状： (1, 2, 3)

加法结果：
[[[11 21 31]
  [42 52 62]]

 [[13 23 33]
  [44 54 64]]

 [[15 25 35]
  [46 56 66]]]


### **有限状态机题目**

设计一个有限状态机 (FSM) 来验证输入字符串是否由一个或多个 `'a'` 开始，接着是一个或多个 `'b'`，最后以一个 `'c'` 结束。字符串的形式必须是：

\[
\text{模式: } a^+b^+c
\]

- \(a^+\)：表示一个或多个 `'a'`。
- \(b^+\)：表示一个或多个 `'b'`。
- \(c\)：表示字符串必须以单个 `'c'` 结尾。

---

### **任务**

1. 使用一个状态转换表来定义 FSM。
2. 起始状态为 `0`。
3. 接受状态为 `[3]`。
4. 如果输入字符串满足模式要求，FSM 最终落在接受状态；否则，拒绝该字符串。
5. 编写代码实现 FSM 并验证以下输入字符串：

    ```plaintext
    'aabbc'   -> Accepted
    'abc'     -> Accepted
    'abbc'    -> Accepted
    'aabc'    -> Accepted
    'aac'     -> Rejected
    'aabb'    -> Rejected
    'ac'      -> Rejected
    ```

---

### **示例代码框架**

```python
def fsm(input_string):
    # 定义状态转换表
    transition_table = {
        0: {'a': 1},
        1: {'a': 1, 'b': 2},
        2: {'b': 2, 'c': 3},
        3: {}
    }
    start_state = 0
    end_states = [3]

    # 初始化当前状态
    current_state = start_state

    # 遍历输入字符串
    for char in input_string:
        if char in transition_table[current_state]:
            current_state = transition_table[current_state][char]
        else:
            return "Rejected"

    # 检查是否到达接受状态
    return "Accepted" if current_state in end_states else "Rejected"

# 测试字符串
test_strings = ['aabbc', 'abc', 'abbc', 'aabc', 'aac', 'aabb', 'ac']
for string in test_strings:
    print(f"Input: {string}, Result: {fsm(string)}")
```

---

### **提示**

1. **状态转换表设计**：
   - \(0 \to 1\)：读到 `'a'` 时，从初始状态转移到状态 `1`。
   - \(1 \to 1\)：连续读到 `'a'` 时，保持在状态 `1`。
   - \(1 \to 2\)：读到 `'b'` 时，转移到状态 `2`。
   - \(2 \to 2\)：连续读到 `'b'` 时，保持在状态 `2`。
   - \(2 \to 3\)：读到 `'c'` 时，转移到接受状态 `3`。

2. **终止条件**：
   - 必须完整读取输入字符串，并且最终状态必须是接受状态 `3`。

完成后，运行代码验证 FSM 是否正确工作。

In [121]:
t_table = {
    0: {'a': 1},
    1: {'a':1,'b':2},
    2: {'b':2,'c':3},
    3: {'a':0}
}

start_state = 0
end_state = [3]

In [122]:
start_state = 0
end_state = [3]
class FSM:
    def __init__(self,table) -> None:
        self.t_table = table
        self.state = 0
        self.label = 'a'
    
    def validation(self, words):
        self.state = start_state
        for char in words:
            try:
                self.state = t_table[self.state][char]
            except:
                return False
        return self.state in end_state


In [123]:
test_strings = ['aabbc', 'abc', 'abbc', 'aabc', 'aac', 'aabb', 'ac']


fsm = FSM(t_table)

for string in test_strings:
    print(f"Input: {string}, Result: {fsm.validation(string)}")

Input: aabbc, Result: True
Input: abc, Result: True
Input: abbc, Result: True
Input: aabc, Result: True
Input: aac, Result: False
Input: aabb, Result: False
Input: ac, Result: False


### **题目：使用生成器实现图的广度优先遍历 (BFS)**

#### **问题描述**

给定一个无向图，用字典表示为邻接表格式，例如：

```python
graph = {
    'A': ['B', 'C'],
    'B': ['A', 'D', 'E'],
    'C': ['A', 'F'],
    'D': ['B'],
    'E': ['B', 'F'],
    'F': ['C', 'E']
}
```

1. 编写一个生成器函数 `bfs(graph, start)` 来实现广度优先遍历（BFS）。
2. `bfs(graph, start)` 按层次生成每个节点，例如从起始节点 `'A'` 开始，输出顺序为：
   ```
   A, B, C, D, E, F
   ```
3. 使用 `yield` 在每次访问一个节点时返回该节点，而不是一次性返回整个遍历结果。
4. 编写一个主程序调用生成器并输出遍历的节点顺序。

---

### **输入与输出**

- **输入**：
  - 图：使用字典表示邻接表。
  - 起始节点：例如 `'A'`。
- **输出**：
  - 按照 BFS 遍历顺序逐个生成节点。

---

### **示例代码框架**

```python
def bfs(graph, start):
    """
    使用生成器实现广度优先遍历
    :param graph: 图的邻接表表示
    :param start: 起始节点
    """
    # 实现 BFS
    pass

# 示例图
graph = {
    'A': ['B', 'C'],
    'B': ['A', 'D', 'E'],
    'C': ['A', 'F'],
    'D': ['B'],
    'E': ['B', 'F'],
    'F': ['C', 'E']
}

# 调用生成器并打印节点
for node in bfs(graph, 'A'):
    print(node)
```

---

### **预期输出**

对于输入图 `graph` 和起始节点 `'A'`，输出顺序应为：

```plaintext
A
B
C
D
E
F
```

---

### **提示**

1. 使用队列（`collections.deque`）来辅助 BFS 实现。
2. 使用集合记录访问过的节点，避免重复访问。
3. 每次访问一个节点后，使用 `yield` 返回该节点。

In [ ]:
def bfs(graph, start):
    """
    使用生成器实现广度优先遍历
    :param graph: 图的邻接表表示
    :param start: 起始节点
    """
    # 实现 BFS
    pass

# 示例图
graph = {
    'A': ['B', 'C'],
    'B': ['A', 'D', 'E'],
    'C': ['A', 'F'],
    'D': ['B'],
    'E': ['B', 'F'],
    'F': ['C', 'E']
}

# 调用生成器并打印节点
for node in bfs(graph, 'A'):
    print(node)

### **题目：使用生成器实现图的深度优先遍历 (DFS)**

#### **问题描述**

给定一个无向图，用字典表示为邻接表格式，例如：

```python
graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}
```

1. 编写一个生成器函数 `dfs(graph, start)` 来实现深度优先遍历（DFS）。
2. `dfs(graph, start)` 按深度优先的顺序生成节点。例如从起始节点 `'A'` 开始，输出顺序为：
   ```
   A, B, D, E, F, C
   ```
3. 使用 `yield` 在每次访问一个节点时返回该节点，而不是一次性返回整个遍历结果。
4. 编写一个主程序调用生成器并输出遍历的节点顺序。

---

### **输入与输出**

- **输入**：
  - 图：使用字典表示邻接表。
  - 起始节点：例如 `'A'`。
- **输出**：
  - 按照 DFS 遍历顺序逐个生成节点。

---

### **示例代码框架**

```python
def dfs(graph, start, visited=None):
    """
    使用生成器实现深度优先遍历
    :param graph: 图的邻接表表示
    :param start: 起始节点
    :param visited: 已访问节点的集合
    """
    # 实现 DFS
    pass

# 示例图
graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

# 调用生成器并打印节点
for node in dfs(graph, 'A'):
    print(node)
```

---

### **预期输出**

对于输入图 `graph` 和起始节点 `'A'`，输出顺序应为：

```plaintext
A
B
D
E
F
C
```

---

### **提示**

1. 使用递归函数实现 DFS。
2. 使用集合记录访问过的节点，避免重复访问。
3. 在访问节点后，使用 `yield` 返回该节点。
4. 对于每个节点的邻居，按照它们在邻接表中的顺序依次递归访问。

完成后，你将能够使用生成器优雅地实现图的深度优先遍历！

In [136]:
def dfs(graph, start, visited=None):
    """
    使用生成器实现深度优先遍历
    :param graph: 图的邻接表表示
    :param start: 起始节点
    :param visited: 已访问节点的集合
    """
    # 实现 DFS
    visited = set()
    def _helper(graph,node):
        if node in visited: return
        visited.add(node)
        yield node
        
        for n in graph[node]:
            yield from _helper(graph,n)
    
    yield from _helper(graph, start)

# 示例图
graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

# 调用生成器并打印节点
for node in dfs(graph, 'A'):
    print(node)

A
B
D
E
F
C


### **问题描述：广播机制的变形**

给定以下数组 `x`，设计一个数组 `y`，使得 `x + y` 的结果符合给定的输出。

```python
import numpy as np

x = np.array([[1, 2, 3],
              [4, 5, 6]])

# y = ?
result = x + y

# 预期输出
array([[ 2,  4,  6],
       [ 5,  7,  9]])
```

---

### **任务**

1. 根据 `result` 推导出数组 `y` 的形式（考虑广播机制）。
2. 编写代码验证 `x + y` 的结果是否符合预期。
3. 使用这个例子解释 NumPy 广播规则。

---

### **提示**

1. **数组分析**：
   - `x` 的形状为 `(2, 3)`。
   - `y` 的形状需要与 `x` 广播兼容。

2. **设计 `y` 的策略**：
   - 考虑 `y` 是否可以是：
     - 一维数组（形状为 `(3,)`）。
     - 二维数组（形状为 `(2, 3)`）。
     - 甚至标量值（形状为 `()`）。

3. **广播规则**：
   - 如果数组的维度不同，NumPy 会在较小维度的前面填充维数 `1`。
   - 每个维度上，数组中大小为 `1` 的维度会被扩展为另一个数组的大小。

---

### **代码框架**

```python
import numpy as np

x = np.array([[1, 2, 3],
              [4, 5, 6]])

# 填写数组 y
y = ...

# 计算结果
result = x + y

# 打印结果验证
print("x:")
print(x)
print("\ny:")
print(y)
print("\nResult:")
print(result)
```

完成后，解释广播机制是如何使得 `x + y` 能够正常计算的，并确保代码运行结果符合预期输出。

In [125]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])

# 填写数组 y
y = [[1,2,3]]

# 计算结果
result = x + y

# 打印结果验证
print("x:")
print(x)
print("\ny:")
print(y)
print("\nResult:")
print(result)

x:
[[1 2 3]
 [4 5 6]]

y:
[[1, 2, 3]]

Result:
[[2 4 6]
 [5 7 9]]


### **题目：将循环操作改为 NumPy 向量化**

#### **问题描述**

给定以下代码片段，它使用了循环操作。你的任务是将其改写为 NumPy 的向量化形式，以提高代码的效率。

```python
# 示例代码
L = [1.2, 2.3, 3.4, 4.5, 5.6]

# 使用循环计算平方和
result = 0
for value in L:
    result += value ** 2

print("Result:", result)
```

---

### **任务**

1. 将以上代码片段改写为使用 NumPy 的向量化操作来完成。
2. 假设输入 `L` 是一个 Python 的浮点数列表（如上例所示），在你的实现中，确保结果一致。
3. 编写代码验证你的实现是否正确。

---

### **示例输入与输出**

#### 输入：
```python
L = [1.2, 2.3, 3.4, 4.5, 5.6]
```

#### 输出：
```plaintext
Result: 68.34
```

---

### **提示**

1. 使用 NumPy 的 `np.array` 将列表转换为数组。
2. 使用 NumPy 的广播和矢量化计算来完成平方和操作。

---

### **代码框架**

```python
import numpy as np

# 输入列表
L = [1.2, 2.3, 3.4, 4.5, 5.6]

# 使用 NumPy 实现向量化操作计算平方和
result = ...

# 输出结果
print("Result:", result)
```

完成后，运行代码并验证是否与循环版本的结果一致。

In [ ]:
start_state = 0

trans_table = {
    0: {'a':1},
    1:{'a':2,'b':0},
    2:{'a':3,'b':0},
    3:{'a':4,'b':0},
    4:{'a':'success'}
}
end_state = [4]

The following code fragment uses loops. Rewrite the fragment in a Numpy vectorised style. Assume L is a list of float values.

1. 
```python
avg = sum(L) / len(L)
count = 0
for val in L:
    if val > avg:
        count += 1
```
2. 
```python
total = 0
for i in range(len(L) - 1):
    total += abs(L[i] - L[i+1])
```
3. 
```python
count = 0
for i in range(len(L) - 1):
    if L[i] == L[i+1]:
        count += 1
```

In [141]:

L = [1,2,3,4,5,6,7]
x= np.array(L)
# 1st

avg = sum(x)/ len(x)

counts = np.sum(x>avg) 

# 2nd
diff = np.sum(np.abs(x[:-1]-x[1:]))
diff


6

### EVAL

Here are some exercises related to the `eval()` function in Python. These exercises focus on evaluating dynamically generated expressions, converting strings into Python objects, and understanding the risks and safe practices when using `eval()`.

---

### **Basic Exercises**

#### **1. Evaluate Arithmetic Expressions**
Write a program that takes a string representing an arithmetic expression (e.g., `"3 + 5 * (2 - 1)"`) and evaluates it using `eval()`.

```python
# Input: "3 + 5 * (2 - 1)"
# Output: 8
```

---

#### **2. Convert a String into a List**
Given a string representation of a list (e.g., `"[1, 2, 3, 4]"`), use `eval()` to convert it into an actual Python list.

```python
# Input: "[1, 2, 3, 4]"
# Output: [1, 2, 3, 4]
```

---

#### **3. Evaluate a User-Defined Function**
Ask the user to input a function in terms of `x` (e.g., `"x**2 + 2*x + 1"`) and evaluate it for a given value of `x`.

```python
# Input function: "x**2 + 2*x + 1"
# Value of x: 3
# Output: 16
```

---

#### **4. Evaluate Dictionary Strings**
Given a string that represents a dictionary (e.g., `"{'a': 1, 'b': 2}"`), use `eval()` to convert it into an actual dictionary.

```python
# Input: "{'a': 1, 'b': 2}"
# Output: {'a': 1, 'b': 2}
```

---

#### **5. Safely Evaluate Literal Structures**
Use `ast.literal_eval()` instead of `eval()` to safely parse strings representing basic Python literal structures (e.g., numbers, lists, tuples, dictionaries).

```python
# Input: "[1, 2, 3, {'key': 'value'}]"
# Output: [1, 2, 3, {'key': 'value'}]
# Note: Ensure it raises an error for unsafe expressions like "__import__('os').system('rm -rf /')"
```

---

### **Advanced Exercises**

#### **6. Validate Expressions**
Write a program that takes a string input and evaluates it only if it is a valid mathematical expression. For example, reject expressions with dangerous code like `os.system()`.

```python
# Input: "2 + 3 * (5 - 2)"
# Output: 11

# Input: "__import__('os').system('ls')"
# Output: "Invalid expression!"
```

---

#### **7. Evaluate Multiple Expressions**
Take a list of strings, each representing a mathematical expression, and use `eval()` to compute the result for each.

```python
# Input: ["2 + 2", "3 * 4", "10 / 2"]
# Output: [4, 12, 5.0]
```

---

#### **8. Dynamic Variable Assignment**
Given a string input like `"x = 10; y = x * 2"`, use `eval()` to execute it and print the values of `x` and `y`.

```python
# Input: "x = 10; y = x * 2"
# Output: x = 10, y = 20
```

---

#### **9. Create a Simple Calculator**
Create a calculator program that accepts strings of arithmetic expressions (e.g., `"5 + 3"`) and uses `eval()` to compute the result. Add error handling for invalid expressions.

```python
# Input: "5 + 3"
# Output: 8

# Input: "5 / 0"
# Output: "Error: Division by zero"
```

---

#### **10. Generate and Evaluate Python Code**
Generate a string of Python code dynamically (e.g., creating a loop or defining a function) and execute it using `eval()`. For example:

```python
# Code: "for i in range(5): print(i)"
# Output: 0 1 2 3 4
```

---

### **Key Concepts to Practice**
1. Understand the risks of using `eval()` and learn safer alternatives like `ast.literal_eval()`.
2. Work with dynamically generated code or expressions.
3. Add validation and error handling to avoid executing malicious or invalid code.

If you'd like a solution for any specific exercise, let me know!

In [142]:
s = "3 + 5 * (2 - 1)"
x = eval(s)

x

8

In [147]:
def evaluate_expression(expr,x):
    return eval(expr)
expression = "x**2 + 2*x + 1"

result = evaluate_expression(expression,3)
result


16

### **Exercise: Save and Load Nested Python Structures**

Create a Python program that does the following:

1. Define a nested Python dictionary with lists, strings, and numbers, such as:
   ```python
   data = {
       "user": {
           "name": "Alice",
           "age": 25,
           "hobbies": ["reading", "hiking", "coding"]
       },
       "scores": [95, 87, 90],
       "active": True
   }
   ```

2. Save this dictionary into a file using `repr()`.

3. Read the file content back into a Python object using `eval()`.

4. Verify that the original dictionary and the reconstructed dictionary are identical.

---

### **Hints for Solution**

- Use `repr()` to serialize the dictionary:
   ```python
   open("data/nested_data.txt", "w").write(repr(data))
   ```

- Use `eval()` to deserialize the dictionary:
   ```python
   reconstructed_data = eval(open("data/nested_data.txt").read())
   ```

- Use the `==` operator to compare the two dictionaries:
   ```python
   assert data == reconstructed_data
   ```

---

### **Expected Output**
If the program is correct, the comparison should pass, confirming that the original and reconstructed dictionaries are identical. For example:

```python
Original: {'user': {'name': 'Alice', 'age': 25, 'hobbies': ['reading', 'hiking', 'coding']}, 'scores': [95, 87, 90], 'active': True}
Reconstructed: {'user': {'name': 'Alice', 'age': 25, 'hobbies': ['reading', 'hiking', 'coding']}, 'scores': [95, 87, 90], 'active': True}
Are they identical? True
```

---

**Bonus Challenge**:
Rewrite the same program using `json` instead of `repr()` and `eval()` for safer handling of the nested data.

In [148]:
data = {
       "user": {
           "name": "Alice",
           "age": 25,
           "hobbies": ["reading", "hiking", "coding"]
       },
       "scores": [95, 87, 90],
       "active": True
   }

open('eval_test.txt','w').write(repr(data))

y = eval(open('eval_test.txt').read())

y

{'user': {'name': 'Alice',
  'age': 25,
  'hobbies': ['reading', 'hiking', 'coding']},
 'scores': [95, 87, 90],
 'active': True}